# -*- coding: utf-8 -*-
"""Food_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFFMo34zMzLWZyxzx1spADpEwrXZmEsJ
"""

!pip install tensorflow tensorflow-datasets pandas
import os
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt

print("TensorFlow Version:", tf.__version__)

print("\n--- Loading Food-101 Dataset (This avoids manual download/unzip) ---")
(ds_train, ds_test), ds_info = tfds.load(
    'food101',
    split=['train', 'validation'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)


IMAGE_SIZE = 224
NUM_CLASSES = ds_info.features['label'].num_classes
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE


def preprocess_img(image, label):
    """Resizes the image and normalizes pixel values to 0-1."""
    image = tf.image.resize(image, (IMAGE_SIZE, IMAGE_SIZE))
    image = tf.cast(image, tf.float32) / 255.0
    return image, label


ds_train = ds_train.map(preprocess_img, num_parallel_calls=AUTOTUNE)
ds_train = ds_train.shuffle(buffer_size=1000).batch(BATCH_SIZE).prefetch(AUTOTUNE)

ds_test = ds_test.map(preprocess_img, num_parallel_calls=AUTOTUNE)
ds_test = ds_test.batch(BATCH_SIZE).prefetch(AUTOTUNE)

class_names = ds_info.features['label'].names
print(f" loaded {NUM_CLASSES} food classes.")

print("\n--- Building ResNet50 Model for Transfer Learning ---")
base_model = ResNet50(weights='imagenet',
                      include_top=False,
                      input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3))


for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x) # Reduces spatial dimensions
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()
#


EPOCHS = 10
print(f"\n--- Starting Training for {EPOCHS} Epochs on GPU ---")

history = model.fit(
    ds_train,
    epochs=EPOCHS,
    validation_data=ds_test
)

# Save the trained model for later use
MODEL_FILENAME = 'food_recognition_model_tfds.h5'
model.save(MODEL_FILENAME)
print(f"\nModel saved as: {MODEL_FILENAME}")

def mock_calorie_lookup(food_name):
    """Returns a placeholder calorie value per 100g based on food type complexity."""
    if 'cake' in food_name or 'pizza' in food_name or 'pie' in food_name:
        return 300
    elif 'salad' in food_name or 'apple' in food_name or 'broccoli' in food_name:
        return 50
    else:
        return 150


class_names = [f"class_{i}" for i in range(101)]


class_names = [
    "apple_pie", "baby_back_ribs", "baklava", "beef_carpaccio", "beef_tartare",
    "beet_salad", "beignets", "bibimbap", "bread_pudding", "breakfast_burrito",
    "bruschetta", "caesar_salad", "cannoli", "caprese_salad", "carrot_cake",
    "ceviche", "cheesecake", "cheese_plate", "chicken_curry", "chicken_quesadilla",
    "chicken_wings", "chocolate_cake", "chocolate_mousse", "churros", "clam_chowder",
    "club_sandwich", "crab_cakes", "creme_brulee", "croque_madame", "cup_cakes",
    "deviled_eggs", "donuts", "dumplings", "edamame", "eggs_benedict", "escargots",
    "falafel", "filet_mignon", "fish_and_chips", "foie_gras", "french_fries",
    "french_onion_soup", "french_toast", "fried_calamari", "fried_rice", "frozen_yogurt",
    "garlic_bread", "gnocchi", "greek_salad", "grilled_cheese_sandwich", "grilled_salmon",
    "guacamole", "gyoza", "hamburger", "hot_and_sour_soup", "hot_dog", "huevos_rancheros",
    "hummus", "ice_cream", "lasagna", "lobster_bisque", "lobster_roll_sandwich",
    "macaroni_and_cheese", "macarons", "miso_soup", "mussels", "nachos", "omelette",
    "onion_rings", "oysters", "pad_thai", "paella", "pancakes", "panna_cotta",
    "peking_duck", "pho", "pizza", "pork_chop", "poutine", "prime_rib", "pulled_pork_sandwich",
    "ramen", "ravioli", "red_velvet_cake", "risotto", "samosa", "sashimi", "scallops",
    "seaweed_salad", "shrimp_and_grits", "spaghetti_bolognese", "spaghetti_carbonara",
    "spring_rolls", "steak", "strawberry_shortcake", "sushi", "tacos", "takoyaki",
    "tiramisu", "tuna_tartare", "waffles"
]



calorie_map = {name: mock_calorie_lookup(name) for name in class_names}
print("\n--- Calorie Lookup Map Created (Using Placeholder Mock Data) ---")


def predict_and_estimate(image_path, model, class_names, calorie_map, estimated_weight_g=100):
    """
    Predicts the food item from an image file and estimates its calorie content.
    """
    IMAGE_SIZE = 224

    try:
        img_raw = tf.io.read_file(image_path)
        img = tf.image.decode_jpeg(img_raw, channels=3)
    except Exception as e:
        print(f"❌ Error loading image: {e}")
        print("Please upload a valid JPG image to Colab.")
        return None

    img_tensor = tf.image.resize(img, (IMAGE_SIZE, IMAGE_SIZE))
    img_tensor = tf.cast(img_tensor, tf.float32) / 255.0
    img_array = np.expand_dims(img_tensor, axis=0)

    # Predict
    predictions = model.predict(img_array)
    predicted_index = np.argmax(predictions[0])
    confidence = np.max(predictions[0])

    if predicted_index < len(class_names):
        predicted_food_name = class_names[predicted_index]
    else:
        predicted_food_name = f"Unknown_Class_{predicted_index}"
    base_calories = calorie_map.get(predicted_food_name.lower(), 150)
    total_calories = (base_calories / 100.0) * estimated_weight_g

    plt.imshow(img.numpy().astype("uint8"))
    plt.title(f"Prediction: {predicted_food_name} ({confidence*100:.2f}%)")
    plt.axis('off')
    plt.show()

    return {
        "Predicted Food": predicted_food_name,
        "Confidence": f"{confidence*100:.2f}%",
        "Estimated Calories": round(total_calories, 2),
        "Weight Assumption (g)": estimated_weight_g
    }



uploaded_image_path = "//content/food1.jpg"
estimated_weight = 64

print("\n--- Testing Prediction and Calorie Estimation ---")


model = tf.keras.models.load_model("/content/food_recognition_model_tfds.h5")
print("Model Loaded Successfully!")
print("Model output shape:", model.output_shape)

# Predict
results = predict_and_estimate(uploaded_image_path, model, class_names, calorie_map, estimated_weight)

print("\n--- Prediction Results ---")
print(results)



